name: Test

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
           deno-version: v1.x
      - name: Run linter
        run: deno lint
      - name: Checking files format
        run: deno fmt --check
      - name: Run unit tests
        run: deno test --allow-net
